// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrnvbgzlzjkibwnndsaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybnZiZ3psempraWJ3bm5kc2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDAxODgsImV4cCI6MjA2OTc3NjE4OH0.lwJ7i0HAHxcZW3fMm8IfiinuJqdFbx9y2qQ2P6he4_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});